### ISSUE TITLE
Possible bug with MPRAREV tag for reverse orientation

### ISSUE THREAD

**Issue by cbenway** [andrewGhazi/mpradesigntools#1]
Hi Andrew,

I've run into an issue when I try to use the MPRAREV tag in the INFO field of the VCF:

> Error in mutate_impl(.data, dots) : 
  Evaluation error: unable to find an inherited method for function 'reverseComplement' for signature '"character"'.

Also it looks like the dbSNP Batch Query service is now discontinued.

Thanks!
Chris

**Comment by andrewGhazi** [comment]
Hi,

Looks like I neglected to change a character string to a Biostrings::DNAString object in some part of program flow for reverse gene constructs. I'll take a look -- this should be an easy fix. Thanks for pointing it out.

Regarding the dbSNP batch query service: I'm aware of this, but I'm still thinking of the best way to proceed. The dbSNP151 VCF and new JSON API (below) report small indels in a slightly different way that doesn't work with the existing package code. For single nucleotide variants they should work fine if that's all you have. I think I'm going to write a new function that can fix indels from the new outputs rather than try to edit the existing indel-handling code. I've done it before manually for separate projects so I should just need to integrate it into the package. 

This may take a little while longer though. I'll shoot for the next two weeks. If you need constructs for indels now, the fix would be to change insertions reported as REF "C", ALT "CAAT" to REF "-", ALT "AAT". Similarly for deletions.

https://api.ncbi.nlm.nih.gov/variation/v0/

Thanks for raising these issues!

**Comment by cbenway** [comment]
Thanks for the quick response!

**Comment by andrewGhazi** [comment]
Can you try it now? I wasn't able to recapitulate this behaviour with my own tests but I think I fixed the source of the problem in the latest commit.

If it's still not working, have you identified / can you identify and share a specific variant causing this? Also could you give the output of sessionInfo()?

**Comment by cbenway** [comment]
Hi Andrew,

I realized that I never replied- yes! The MPRAREV tag works great now.

On a separate issue- we find that a significant proportion of SNPs we are
interested in designing are failing due to context containing restriction
sites. Have you considered any programmatic options for dealing with this
problem? I think our strategy going forward would be to mutate the
restriction site if possible. It would be helpful to be able to override
the design fail in the package so that the context sequence around the SNP
is still pulled from the reference and the oligo with barcodes designed so
that I have that output to work with.

Thanks for your help!
Chris

**Comment by andrewGhazi** [comment]
Great, closing this issue then.

Regarding aberrant sites: reinstall and see the (newly added and possibly buggy) alter_aberrant option of processVCF(). Randomly mutating the sites like you suggest is exactly what it does. It has some limitations (only checks the context for aberrant sites, not the interface between elements) but it seems to fix a good fraction of failures in my own tests.
