### ISSUE TITLE
Error in if (!grepl(",", snp$ALT)) { : argument is of length zero

### ISSUE THREAD

**Issue by yalongan** [andrewGhazi/mpradesigntools#3]
Hello, when I run mpradesigntools, there is such an error, how should I solve it, can you help me to point out? Thank you!Error in if (!grepl(",", snp$ALT)) { : argument is of length zero                                                            
In addition: Warning message:
Unknown or uninitialised column: `ALT`.

**Comment by andrewGhazi** [comment]
This is indicating that this `grepl()` call [1]  in `spreadAllelesAcrossRows()` was failing, probably because the `snp` argument passed to it was empty, probably because the input was incorrectly formatted. You might want to try `debug(processVCF)` and then step through the function call to check that the `vcf` variable here [2] is formatted in the way you expect.

[1] https://github.com/andrewGhazi/mpradesigntools/blob/master/R/processVCFfast.R#L9
[2] https://github.com/andrewGhazi/mpradesigntools/blob/master/R/processVCFfast.R#L1134
