### ISSUE TITLE
Other species, not people

### ISSUE THREAD

**Issue by yalongan** [andrewGhazi/mpradesigntools#4]
Dear andrewGhazi:
Hello, I want to use mpradesigntools to design barcode sequence in other species, how to use it, can you help me to answer it.

**Comment by andrewGhazi** [comment]
In order to use the package for something other than human genomes there are a lot of little details that would need to be checked, which I'm unable to do at this time. In principle one would need to update any references to `BSgenome.Hsapiens.UCSC.hg38` (e.g. the line below) to the requisite genome, so you might give that a try if you know your way around R package development.  

https://github.com/andrewGhazi/mpradesigntools/blob/master/R/processVCFfast.R#L227

**Comment by yalongan** [comment]
Thank you very much,

I tried it and it worked. It's a really good package.

________________________________
发件人: Andrew Ghazi ***@***.***>
发送时间: 2023年7月5日 22:44
收件人: andrewGhazi/mpradesigntools ***@***.***>
抄送: yalongan ***@***.***>; Author ***@***.***>
主题: Re: [andrewGhazi/mpradesigntools] Other species, not people (Issue #4)


In order to use the package for something other than human genomes there are a lot of little details that would need to be checked, which I'm unable to do at this time. In principle one would need to update any references to BSgenome.Hsapiens.UCSC.hg38 (e.g. the line below) to the requisite genome, so you might give that a try if you know your way around R package development.

https://github.com/andrewGhazi/mpradesigntools/blob/master/R/processVCFfast.R#L227

―

**Comment by andrewGhazi** [comment]
Cool. There may be some other places in the code where I've implicitly encoded references to the human genome, so I encourage you take a few of the output sequences and manually check them down to individual nucleotides to ensure that they are accurate / what you intend. Just because the code runs without producing an error doesn't necessarily mean that the result is perfectly correct.

**Comment by yalongan** [comment]
Okay, I'll check them off later,

Thank you so much for your great patience and huge help.
________________________________
发件人: Andrew Ghazi ***@***.***>
发送时间: 2023年7月5日 23:42
收件人: andrewGhazi/mpradesigntools ***@***.***>
抄送: yalongan ***@***.***>; Author ***@***.***>
主题: Re: [andrewGhazi/mpradesigntools] Other species, not people (Issue #4)


Cool. There may be some other places in the code where I've implicitly encoded references to the human genome, so I encourage you take a few of the output sequences and manually check them down to individual nucleotides to ensure that they are accurate / what you intend. Just because the code runs without producing an error doesn't necessarily mean that the result is perfectly correct.

―
