### ISSUE TITLE
Server error (Shiny App and R package)

### ISSUE THREAD

**Issue by trprice08** [andrewGhazi/mpradesigntools#5]
I have attempted to use both the Shiny App and the Rpackage to design sequences. 
For the app, my vcf is uploaded and processed but I get a "disconnected from server" error when it appears to try generating the sequences. 

I also tried running the R package and get the following error: 
[1] "Filtering barcode set to ensure that all barcodes contain all four nucleotides..."                                                              
[1] "Removed 5386 barcodes out of 157197 (3.43%)"
[1] "Filtering undesired barcode patterns..."
[1] "Removed 0 barcodes from the usable pool out of the original 151811 (0%)"
[1] "Processing SNPs..."
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'subseq': no such sequence

Any help navigating these errors will be greatly appreciated.

**Comment by andrewGhazi** [comment]
From your error message I can tell that it failed when calling `Biostrings::subseq()` while trying to generate sequences for one of your SNPs, but not much more than that. I think you may have malformed entries in the CHROM field as e.g. `chr5` instead of `5` like the package expects.

If you're comfortable getting into the weeds with R code, you might try calling `debug(mpradesigntools::processVCF)`, and stepping through the function to observe where it goes wrong.

I wrote this package a long time ago when I didn't know much about developing robust code, so it's vulnerable to improperly formatted inputs which is where I'd guess your problem lies. It reads in the VCF as a TSV and mostly focuses on the CHROM, POS, ID, REF, and ALT columns. Any complications to that basic formula (like header info with the wrong comment character, complicated indel variants, multiple alternates, `chr5` instead of `5` in CHROM, etc) will probably make it go off the rails.

I should probably archive this repository soon as I don't have adequate bandwidth to maintain it at this point unfortunately.

**Comment by trprice08** [comment]
Thank you for responding! I will look a bit further into the Rcode and see if there are some issues with formatting.
